export const inspectorHelpText = {
    fullContext: "[CC] 선택한 이벤트의 본문입니다. body가 없으면 description, command, result, action, ruleId 순서로 대체해서 보여줍니다.",
    ids: "[CC] Event는 개별 이벤트 ID, Task는 작업 ID, Session은 Claude Code 런타임 세션 ID(재개 키), Time은 로컬 기록 시각입니다.",
    evidence: "[CC] 이 이벤트가 얼마나 신뢰할 만한지 나타냅니다. hook 원본인지, transcript 복원인지, 파생 이벤트인지와 runtime source를 함께 봐서 high/medium/low로 계산합니다.",
    classificationMatches: "[CC] @monitor/core action-registry 규칙이 이 이벤트를 어떤 의미로 분류했는지 보여줍니다. ruleId를 누르면 같은 규칙 이벤트를 타임라인에서 따라갈 수 있습니다.",
    metadata: "[CC] 전용 카드가 풀어주지 않은 원본 metadata JSON입니다. 수집 payload를 그대로 확인할 때 쓰는 탈출구입니다.",
    connectedEvents: "[CC] 선택한 connector가 실제로 이어주는 source/target 이벤트 쌍입니다. explicit relation인지 fallback sequence인지 함께 확인할 수 있습니다.",
    relatedEvents: "[CC] parentEventId / relatedEventIds 메타데이터로 링크된 주변 이벤트들입니다.",
    model: "[CC] transcript나 hook 메타데이터에서 읽은 모델 이름과 provider입니다.",
    tokenUsage: "[CC] Stop hook이 assistant.response에 붙인 Anthropic usage입니다. input/output/cache read/cache create와 stop reason을 한 턴 단위로 보여줍니다.",
    captureInfo: "[CC] user.message가 raw hook에서 바로 잡힌 입력인지, transcript에서 복원한 입력인지와 source/phase/messageId를 보여줍니다.",
    taskReminder: "[CC] transcript attachment의 task_reminder를 파싱한 결과입니다. status, subject, blocks, blockedBy를 Claude Code 작업 리마인더 기준으로 렌더합니다.",
    subagent: "[CC] 서브에이전트 실행 메타데이터입니다. agent type/id, parent-child task 연결, async status를 확인할 수 있습니다.",
    questionFlow: "[CC] 같은 questionId의 asked / answered / concluded 흐름을 시간순으로 묶은 것입니다. answered는 응답 완료, concluded는 명시적 종료를 뜻합니다.",
    todoLifecycle: "[CC] 같은 todoId의 상태 전이를 시간순으로 보여줍니다. 현재 상태는 마지막 transition으로 계산합니다.",
    agentActivity: "[CC] coordination lane에서 기록된 delegation, skill, MCP 호출 메타데이터입니다.",
    runtimeSession: "[CC] Claude Code 런타임 세션 정보입니다. 세션 ID와 resume command를 보고 같은 실행 맥락으로 복귀할 수 있습니다.",
    cacheEfficiency: "[CC] task 전체 assistant.response 이벤트를 합산한 캐시 효율입니다. 새 입력 대비 cache read 비율을 요약합니다.",
    aiModel: "[CC] 이 task에서 관측된 모델 분포입니다. 가장 많이 등장한 모델을 기본 모델처럼 강조합니다.",
    skillListing: "[CC] Claude Code가 instructions.loaded 시점에 로드한 skill_listing attachment 요약입니다. 세션 초반 스킬 환경을 빠르게 확인할 수 있습니다.",
    taskFlow: "[CC] 작업 지속 시간, 이벤트 수, 세션 수처럼 task 전체 흐름을 요약한 지표입니다.",
    signals: "[CC] 프롬프트, 생각, 툴 호출, 검증, coordination 같은 관측 신호를 종류별로 집계한 카드입니다.",
    subagentsBackground: "[CC] delegation과 background async task가 얼마나 발생했는지 요약합니다.",
    hookCoverage: "[CC] Claude Code hook entrypoint가 현재 task에서 실제로 관측됐는지 보여줍니다. 계측 누락 여부를 빠르게 찾을 때 유용합니다.",
    verificationCycles: "[CC] verification.logged / rule.logged 이벤트를 순서대로 묶어 pass와 issue 흐름을 보여줍니다.",
    todosSummary: "[CC] task 전체 todo를 현재 상태 기준으로 요약합니다. open은 진행 중인 일, done은 completed/cancelled입니다.",
    questionsSummary: "[CC] task 전체 질문을 최신 phase 기준으로 요약합니다. answered면 resolved, concluded면 명시적으로 닫힌 상태입니다.",
    phaseBreakdown: "[CC] lane별 이벤트 분포를 요약해 어느 단계에 시간이 몰렸는지 보여줍니다.",
    topFiles: "[CC] 가장 자주 탐색/수정된 파일입니다. 현재 task가 실제로 어디에 집중됐는지 보여줍니다.",
    instructionsLoaded: "[CC] Claude Code가 세션 시작, 재개, compact 이후에 컨텍스트로 로드한 instruction/skill/deferred-tools/MCP/nested-memory 이벤트들입니다.",
    contextSaved: "[CC] compact 외의 context.saved 이벤트입니다. task_reminder 같은 ad-hoc 저장 컨텍스트를 모아 보여줍니다.",
} as const;
