export const TASK_LIFECYCLE_ACCESS_PORT = "SESSION_TASK_LIFECYCLE_ACCESS_PORT";
export const NOTIFICATION_PUBLISHER_PORT = "SESSION_NOTIFICATION_PUBLISHER_PORT";
export { CLOCK_PORT, ID_GENERATOR_PORT } from "@monitor/shared/kernel/clock.js";
