
export const SESSION_ACCESS_PORT = "TASK_SESSION_ACCESS_PORT";
export const TURN_QUERY_ACCESS_PORT = "TASK_TURN_QUERY_ACCESS_PORT";
export const RUNTIME_BINDING_ACCESS_PORT = "TASK_RUNTIME_BINDING_ACCESS_PORT";
export const NOTIFICATION_PUBLISHER_PORT = "TASK_NOTIFICATION_PUBLISHER_PORT";
export { CLOCK_PORT, ID_GENERATOR_PORT } from "@monitor/shared/kernel/clock.js";
