export const EVENT_PERSISTENCE_PORT = "EVENT_PERSISTENCE_PORT";
export const NOTIFICATION_PUBLISHER_PORT = "EVENT_NOTIFICATION_PUBLISHER_PORT";
export const EVENT_SEARCH_INDEX_PORT = "EVENT_SEARCH_INDEX_PORT";
export { CLOCK_PORT } from "@monitor/shared/kernel/clock.js";
