import type { Provider } from "@nestjs/common";
import type { DataSource } from "typeorm";
import {
    AiJobRepository,
    AiJobStepEntity,
    AiJobStepRepository,
    AppSettingEntity,
    AppSettingRepository,
    AiJobEntity,
    ChatMessageEntity,
    ChatMessageRepository,
    ChatThreadEntity,
    ChatThreadRepository,
    DaemonHealthEntity,
    DaemonHealthRepository,
    EventEntity,
    EventRepository,
    MemoEntity,
    MemoRepository,
    RecipeApplicationEntity,
    RecipeApplicationRepository,
    RecipeEntity,
    RecipeRepository,
    RuleEntity,
    RuleRepository,
    SessionEntity,
    SessionRepository,
    TagEntity,
    TagRepository,
    TaskCleanupSuggestionEntity,
    TaskCleanupSuggestionRepository,
    TaskEntity,
    TaskRepository,
    TaskTagEntity,
    TaskTagRepository,
    TaskUserStateEntity,
    TaskUserStateRepository,
    TransactionRunner,
    TurnEntity,
    TurnRepository,
    UserEntity,
    UserRepository,
    VerdictEntity,
    VerdictRepository,
} from "@monitor/tracer-domain";
import { TRACER_DATA_SOURCE } from "~tracer-api/config/tracer.datasource.token.js";

/** 읽기 모델 저장소를 TRACER_DATA_SOURCE에 연결해 앱 전역에 공급한다. */
export const repositoryProviders: Provider[] = [
    { provide: TaskRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new TaskRepository(ds.getRepository(TaskEntity)) },
    { provide: TaskUserStateRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new TaskUserStateRepository(ds.getRepository(TaskUserStateEntity)) },
    { provide: SessionRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new SessionRepository(ds.getRepository(SessionEntity)) },
    { provide: EventRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new EventRepository(ds.getRepository(EventEntity)) },
    { provide: TurnRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new TurnRepository(ds.getRepository(TurnEntity)) },
    { provide: RuleRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new RuleRepository(ds.getRepository(RuleEntity)) },
    { provide: VerdictRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new VerdictRepository(ds.getRepository(VerdictEntity)) },
    { provide: RecipeRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new RecipeRepository(ds.getRepository(RecipeEntity)) },
    { provide: RecipeApplicationRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new RecipeApplicationRepository(ds.getRepository(RecipeApplicationEntity)) },
    { provide: TaskCleanupSuggestionRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new TaskCleanupSuggestionRepository(ds.getRepository(TaskCleanupSuggestionEntity)) },
    { provide: AiJobRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new AiJobRepository(ds.getRepository(AiJobEntity)) },
    { provide: AiJobStepRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new AiJobStepRepository(ds.getRepository(AiJobStepEntity)) },
    { provide: UserRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new UserRepository(ds.getRepository(UserEntity)) },
    { provide: AppSettingRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new AppSettingRepository(ds.getRepository(AppSettingEntity)) },
    { provide: TransactionRunner, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new TransactionRunner(ds) },
    { provide: DaemonHealthRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new DaemonHealthRepository(ds.getRepository(DaemonHealthEntity)) },
    { provide: MemoRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new MemoRepository(ds.getRepository(MemoEntity)) },
    { provide: TagRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new TagRepository(ds.getRepository(TagEntity)) },
    { provide: TaskTagRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new TaskTagRepository(ds.getRepository(TaskTagEntity)) },
    { provide: ChatThreadRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new ChatThreadRepository(ds.getRepository(ChatThreadEntity)) },
    { provide: ChatMessageRepository, inject: [TRACER_DATA_SOURCE], useFactory: (ds: DataSource) => new ChatMessageRepository(ds.getRepository(ChatMessageEntity)) },
];
