export const TASK_SNAPSHOT_QUERY = "TASK_SNAPSHOT_QUERY";
export const TASK_SUMMARY = "TASK_SUMMARY";
export const TASK_MAINTENANCE = "TASK_MAINTENANCE";

export const TURN_QUERY_REPOSITORY_TOKEN = "TURN_QUERY_REPOSITORY";
