/**
 * DI tokens for the rule module's outbound dependencies.
 */
export const RULE_PERSISTENCE_PORT = "RULE_PERSISTENCE_PORT";
export const NOTIFICATION_PUBLISHER_PORT = "RULE_NOTIFICATION_PUBLISHER_PORT";
export const BACKFILL_TRIGGER_PORT = "RULE_BACKFILL_TRIGGER_PORT";
export const VERIFICATION_INVALIDATION_PORT = "RULE_VERIFICATION_INVALIDATION_PORT";
export const VERDICT_COUNT_QUERY_PORT = "RULE_VERDICT_COUNT_QUERY_PORT";
