import type React from "react";
import { cn } from "../../lib/ui/cn.js";

interface CacheEfficiencyBarProps {
    /**
     * The raw Anthropic `input_tokens` field. Per the Anthropic Messages API
     * this is ONLY the new (non-cached) input tokens for this turn — it does
     * NOT include tokens that were served from the prompt cache or freshly
     * written to the cache. Treat it as "new input only".
     */
    readonly inputTokens: number;
    /** `cache_read_input_tokens` — tokens served from the prompt cache. */
    readonly cacheReadTokens: number;
    /** `cache_creation_input_tokens` — tokens written to cache this turn. */
    readonly cacheCreateTokens: number;
    /** `output_tokens` — tokens generated by the model. */
    readonly outputTokens: number;
}

/**
 * Visualizes token usage for one assistant turn as a stacked bar.
 *
 * Anthropic Messages API token fields (see packages/core/docs/anthropic-usage):
 *   - input_tokens                 : NEW input tokens only (uncached)
 *   - cache_read_input_tokens      : tokens served from prompt cache (fast path)
 *   - cache_creation_input_tokens  : tokens written to cache this turn
 *   - output_tokens                : tokens generated by the model
 *
 * Therefore the true total input is:
 *   totalInput = input_tokens + cache_read_input_tokens + cache_creation_input_tokens
 *
 * And cache hit rate is:
 *   hitRate = cache_read_input_tokens / totalInput
 *
 * Historical bug: a previous version divided cache_read_tokens by the raw
 * input_tokens field, which (since input_tokens is only the non-cached delta)
 * produced wildly inflated percentages like 6,348,850% cache hit. The fix is
 * to compute totalInput explicitly and divide by that.
 */
export function CacheEfficiencyBar({
    inputTokens,
    cacheReadTokens,
    cacheCreateTokens,
    outputTokens,
}: CacheEfficiencyBarProps): React.JSX.Element {
    const newInput = Math.max(0, inputTokens);
    const totalInput = newInput + cacheReadTokens + cacheCreateTokens;
    const total = totalInput + outputTokens;
    const hitRate = totalInput > 0
        ? Math.round((cacheReadTokens / totalInput) * 100)
        : 0;

    const pct = (n: number): string =>
        total > 0 ? `${((n / total) * 100).toFixed(1)}%` : "0%";

    return (
        <div className="flex flex-col gap-1.5">
            <div className="flex h-3 overflow-hidden rounded-full bg-[var(--surface-2)]">
                {cacheReadTokens > 0 && (
                    <div
                        className="h-full bg-[var(--ok)]"
                        style={{ width: pct(cacheReadTokens) }}
                        title={`Cache read: ${cacheReadTokens.toLocaleString()} tokens`}
                    />
                )}
                {cacheCreateTokens > 0 && (
                    <div
                        className="h-full bg-[color-mix(in_srgb,var(--ok)_50%,var(--accent))]"
                        style={{ width: pct(cacheCreateTokens) }}
                        title={`Cache write: ${cacheCreateTokens.toLocaleString()} tokens`}
                    />
                )}
                {newInput > 0 && (
                    <div
                        className="h-full bg-[var(--accent)]"
                        style={{ width: pct(newInput) }}
                        title={`New input: ${newInput.toLocaleString()} tokens`}
                    />
                )}
                {outputTokens > 0 && (
                    <div
                        className="h-full bg-[var(--text-3)]"
                        style={{ width: pct(outputTokens) }}
                        title={`Output: ${outputTokens.toLocaleString()} tokens`}
                    />
                )}
            </div>

            <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[0.68rem] text-[var(--text-3)]">
                <LegendItem color="bg-[var(--ok)]" label="Cache read" value={cacheReadTokens} />
                <LegendItem
                    color="bg-[color-mix(in_srgb,var(--ok)_50%,var(--accent))]"
                    label="Cache write"
                    value={cacheCreateTokens}
                />
                <LegendItem color="bg-[var(--accent)]" label="New input" value={newInput} />
                <LegendItem color="bg-[var(--text-3)]" label="Output" value={outputTokens} />
                <span className={cn(
                    "ml-auto font-semibold",
                    hitRate >= 70 ? "text-[var(--ok)]" :
                    hitRate >= 30 ? "text-[var(--warn)]" : "text-[var(--text-2)]"
                )}>
                    {hitRate}% cache hit
                </span>
            </div>
        </div>
    );
}

function LegendItem({ color, label, value }: {
    readonly color: string;
    readonly label: string;
    readonly value: number;
}): React.JSX.Element | null {
    if (value <= 0) return null;
    return (
        <span className="flex items-center gap-1">
            <span className={cn("h-2 w-2 shrink-0 rounded-full", color)} />
            {label}: {value.toLocaleString()}
        </span>
    );
}

/**
 * Computes the cache hit rate percentage (0-100) from raw Anthropic usage
 * numbers. Exported so other surfaces (e.g. the task-level OverviewTab)
 * can display the same metric with identical semantics.
 */
export function computeCacheHitRate(
    inputTokens: number,
    cacheReadTokens: number,
    cacheCreateTokens: number
): number {
    const totalInput = Math.max(0, inputTokens) + cacheReadTokens + cacheCreateTokens;
    return totalInput > 0 ? Math.round((cacheReadTokens / totalInput) * 100) : 0;
}
