export const inspectorHelpText = {
    fullContext: "선택한 이벤트의 본문입니다. 본문이 없으면 description, command, result 같은 대체 필드를 순서대로 골라 보여줍니다. 원문이 실제로 무엇이었는지 확인할 때 봅니다.",
    ids: "이 이벤트를 추적할 때 쓰는 식별자들입니다. Event는 개별 기록, Task는 작업 전체, Session은 같은 런타임 실행 맥락, Time은 이 이벤트가 기록된 시각입니다.",
    evidence: "이 이벤트를 얼마나 믿어도 되는지 요약합니다. Hook 원본인지, transcript에서 복원한 것인지, 다른 데이터에서 파생한 것인지에 따라 신뢰 수준이 달라집니다.",
    classificationMatches: "분류기가 이 이벤트를 어떤 의미로 읽었는지 보여줍니다. 같은 이벤트라도 여러 규칙이 동시에 맞을 수 있고, 각 규칙이 왜 매칭됐는지도 함께 확인할 수 있습니다.",
    metadata: "전용 카드가 풀어서 보여주지 않은 원본 metadata입니다. UI 요약보다 한 단계 아래의 수집 값을 그대로 보고 싶을 때 확인합니다.",
    connectedEvents: "현재 선택한 연결선이 실제로 이어 주는 이벤트 쌍입니다. 어떤 이벤트가 무엇 때문에 연결됐는지, 그리고 그 연결이 명시적 관계인지 추론된 순서 관계인지 읽을 수 있습니다.",
    relatedEvents: "이 이벤트와 메타데이터로 직접 연결된 주변 이벤트들입니다. parentEventId나 relatedEventIds가 있는 경우 그 링크를 따라가 보여줍니다.",
    model: "이 이벤트에 연결된 모델 정보입니다. Hook나 transcript 메타데이터에서 읽은 모델명과 provider를 보여줍니다.",
    captureInfo: "이 user.message가 어디에서 잡힌 입력인지 설명합니다. Hook에서 바로 캡처한 원문인지, transcript에서 나중에 복원한 값인지와 함께 source, phase, messageId를 보여줍니다.",
    taskReminder: "Claude Code transcript에 붙은 task_reminder attachment를 읽기 쉬운 형태로 푼 것입니다. 현재 작업이 무엇을 기억하고 있었는지, 무엇에 막혀 있었는지 확인할 수 있습니다.",
    subagent: "서브에이전트 실행 정보입니다. 어떤 agent가 돌았는지, 부모 task와 어떻게 연결됐는지, 현재 상태가 running/completed 중 무엇인지 보여줍니다.",
    questionFlow: "같은 questionId를 가진 질문 이벤트를 asked → answered → concluded 순서로 묶은 흐름입니다. 질문이 제기됐는지, 답을 받았는지, 명시적으로 닫혔는지를 한 줄로 읽을 수 있습니다.",
    todoLifecycle: "같은 todoId의 상태 변화 기록입니다. 추가, 진행 중, 완료, 취소가 어떤 순서로 일어났는지 보여주며, 현재 상태는 마지막 transition 기준으로 계산합니다.",
    agentActivity: "coordination lane에서 기록된 위임과 호출 정보입니다. 다른 agent에 넘긴 일, 스킬 사용, MCP 호출 같은 조정 행동을 한곳에서 볼 수 있습니다.",
    runtimeSession: "현재 task가 어떤 Claude Code 런타임 세션에 묶여 있는지 보여줍니다. Session ID와 resume command를 보면 같은 실행 맥락으로 다시 붙을 수 있습니다.",
    aiModel: "이 task에서 실제로 관측된 모델 분포입니다. 가장 많이 등장한 모델을 중심으로 보여주며, task가 여러 모델을 섞어 썼는지도 여기서 드러납니다.",
    skillListing: "세션 중 로드된 skill_listing attachment 요약입니다. Claude Code가 어떤 스킬 세트를 활성화한 상태였는지 빠르게 파악할 수 있습니다.",
    taskFlow: "task 전체 흐름을 요약한 지표입니다. 작업이 얼마나 오래 열려 있었는지, 이벤트와 세션이 얼마나 쌓였는지를 한눈에 봅니다.",
    signals: "이 task에서 관측된 신호를 종류별로 집계한 카드입니다. 사용자 입력, 생각, 툴 호출, 검증, coordination 중 어디에 기록이 많이 몰렸는지 볼 수 있습니다.",
    subagentsBackground: "위임과 background 작업이 얼마나 활발했는지 요약합니다. delegation 수, background 이벤트 수, async task 완료/미해결 상태를 같이 보여줍니다.",
    hookCoverage: "Claude Code hook entrypoint가 이 task에서 실제로 관측됐는지 보여줍니다. 특정 hook이 전혀 안 찍혔다면 계측 누락인지, 그 상황이 실제로 없었는지 판단하는 데 도움이 됩니다.",
    verificationCycles: "verification.logged와 rule.logged를 시간순으로 묶은 검사 기록입니다. 어떤 검증이 통과했고 어떤 단계에서 이슈가 났는지 흐름으로 읽을 수 있습니다.",
    todosSummary: "task 전체 todo를 현재 상태 기준으로 묶은 요약입니다. 지금 열려 있는 일이 무엇인지와 이미 끝난 항목이 무엇인지 빠르게 구분할 수 있습니다.",
    questionsSummary: "task 전체 질문을 최신 phase 기준으로 요약합니다. 아직 열려 있는 질문인지, 답을 받았는지, 명시적으로 닫힌 질문인지를 보여줍니다.",
    phaseBreakdown: "lane별 이벤트 분포입니다. planning, exploration, implementation, coordination 중 어디에 기록이 많이 쌓였는지 보여주므로 작업 성격을 읽기 좋습니다.",
    topFiles: "이 task에서 가장 자주 읽거나 수정한 파일입니다. 실제로 작업이 집중된 코드 위치를 빠르게 찾는 용도입니다.",
    instructionsLoaded: "Claude Code가 세션 시작, 재개, compact 이후에 컨텍스트로 불러온 instruction 계열 이벤트입니다. 어떤 규칙, skill, deferred tools, nested memory가 활성화됐는지 확인할 수 있습니다.",
    contextSaved: "compact 경계 외에 별도로 저장된 context입니다. task_reminder, nested memory 같은 보조 컨텍스트가 언제 어떤 내용으로 들어왔는지 보여줍니다.",
    ruleTab: "설정된 rule command가 이 task에서 실제로 실행됐는지 보여줍니다. rule lane 이벤트 중 패턴이 일치하는 것을 찾아 실행 여부와 횟수를 표시합니다. 항목을 클릭하면 해당 타임라인 이벤트로 이동합니다.",
} as const;
