
export const TASK_LIFECYCLE = "TASK_LIFECYCLE";
export const TASK_ACCESS = "TASK_ACCESS";
export const TASK_SNAPSHOT_QUERY = "TASK_SNAPSHOT_QUERY";

export const TURN_QUERY_REPOSITORY_TOKEN = "TURN_QUERY_REPOSITORY";
