#!/usr/bin/env bash
#
# Agent Tracer — global status line installer.
#
# Wraps (or creates) ${HOME}/.claude/statusline-command.sh so that the
# agent-tracer "[monitor] ctx N% · 5h N% · $X" segment is appended after the
# user's existing status line, in *every* project — not just the agent-tracer
# repo.
#
# Why this is needed:
#   Claude Code plugins can register hook events but cannot register a
#   `statusLine` (statusLine is a settings.json-only field). So the plugin
#   alone cannot wire up the status line in arbitrary working directories.
#   This script installs a tiny wrapper that does.
#
# Behavior:
#   - Idempotent: re-running detects the marker and exits cleanly.
#   - Safe: backs up any existing script to *.bak.<unix-ts>.
#   - Preserves: existing status line output is captured and rendered first,
#     with the monitor segment appended in dim grey.
#   - Non-invasive: this script does NOT edit ~/.claude/settings.json. It
#     prints the JSON snippet for the user to add manually.
#
# Prerequisite:
#   The agent-tracer plugin must be installed via the Claude Code marketplace,
#   i.e. ${HOME}/.claude/plugins/marketplaces/agent-tracer/ must exist.

set -euo pipefail

CLAUDE_DIR="${HOME}/.claude"
TARGET="${CLAUDE_DIR}/statusline-command.sh"
ORIGINAL="${CLAUDE_DIR}/statusline-original.sh"
RUNNER="${CLAUDE_DIR}/plugins/marketplaces/agent-tracer/packages/runtime/src/claude-code/bin/run-hook.sh"
MARKER="# AGENT_TRACER_STATUSLINE_WRAPPER v1"

if [ ! -x "$RUNNER" ]; then
  echo "ERROR: agent-tracer plugin runner not found:" >&2
  echo "  $RUNNER" >&2
  echo "" >&2
  echo "Install the plugin first via Claude Code:" >&2
  echo "  /plugin install agent-tracer-monitor" >&2
  exit 1
fi

mkdir -p "$CLAUDE_DIR"

if [ -f "$TARGET" ] && grep -Fq "$MARKER" "$TARGET"; then
  echo "Already installed — wrapper marker found in:"
  echo "  $TARGET"
  echo "Nothing to do."
  exit 0
fi

if [ -f "$TARGET" ]; then
  TS=$(date +%s)
  BACKUP="${TARGET}.bak.${TS}"
  cp "$TARGET" "$BACKUP"
  cp "$TARGET" "$ORIGINAL"
  chmod +x "$ORIGINAL"
  echo "Existing status line backed up:"
  echo "  $BACKUP"
  echo "Existing logic preserved as:"
  echo "  $ORIGINAL  (sourced by the wrapper)"
fi

cat > "$TARGET" <<'WRAPPER'
#!/bin/sh
# AGENT_TRACER_STATUSLINE_WRAPPER v1
# Generated by scripts/install-statusline.sh — do not edit by hand.
# Combines the user's previous status line (if any) with the agent-tracer
# monitor segment. Re-run the installer to update.

input=$(cat)

base=""
if [ -x "${HOME}/.claude/statusline-original.sh" ]; then
  base=$(printf '%s' "$input" | sh "${HOME}/.claude/statusline-original.sh" 2>/dev/null || true)
fi

monitor=""
runner="${HOME}/.claude/plugins/marketplaces/agent-tracer/packages/runtime/src/claude-code/bin/run-hook.sh"
if [ -x "$runner" ]; then
  monitor=$(printf '%s' "$input" | "$runner" StatusLine 2>/dev/null || true)
fi

if [ -n "$base" ] && [ -n "$monitor" ]; then
  printf '%s \033[90m%s\033[0m' "$base" "$monitor"
elif [ -n "$monitor" ]; then
  printf '%s' "$monitor"
else
  printf '%s' "$base"
fi
WRAPPER

chmod +x "$TARGET"

echo ""
echo "Installed wrapper:"
echo "  $TARGET"
echo ""
echo "If your ~/.claude/settings.json does not yet declare a statusLine,"
echo "add this block (top-level key):"
echo ""
cat <<'JSON'
  "statusLine": {
    "type": "command",
    "command": "bash ~/.claude/statusline-command.sh"
  }
JSON
echo ""
echo "Then restart Claude Code."
