#!/usr/bin/env bash
#
# Agent Tracer — global status line installer.
#
# Wraps (or creates) ${HOME}/.claude/statusline-command.sh so that the
# agent-tracer "[monitor] ctx N% · 5h N% · $X" segment is appended after the
# user's existing status line, in *every* project — not just the agent-tracer
# repo.
#
# Why this is needed:
#   Claude Code plugins can register hook events but cannot register a
#   `statusLine` (statusLine is a settings.json-only field). So the plugin
#   alone cannot wire up the status line in arbitrary working directories.
#   This script installs a tiny wrapper that does.
#
# Behavior:
#   - Idempotent: re-running detects the marker and exits cleanly.
#   - Safe: backs up any existing script to *.bak.<unix-ts>.
#   - Preserves: existing status line output is captured and rendered first,
#     with the monitor segment appended in dim grey.
#   - settings.json: by default, NOT edited — the script inspects it,
#     reports the current state (already wired / missing key / pointing
#     elsewhere) and prints the JSON snippet to add. Pass `--apply` to
#     let the script patch settings.json directly (with a timestamped
#     backup). This was added because the "manual edit" step was easy to
#     miss, leaving users with an installed wrapper but no active status
#     line.
#
# Usage:
#   bash scripts/install-statusline.sh [--apply]
#
# Prerequisite:
#   The agent-tracer plugin must be installed via the Claude Code marketplace,
#   i.e. ${HOME}/.claude/plugins/marketplaces/agent-tracer/ must exist.

set -euo pipefail

APPLY=0
for arg in "$@"; do
  case "$arg" in
    --apply) APPLY=1 ;;
    -h|--help)
      sed -n '2,33p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      echo "Usage: $0 [--apply]" >&2
      exit 2
      ;;
  esac
done

CLAUDE_DIR="${HOME}/.claude"
TARGET="${CLAUDE_DIR}/statusline-command.sh"
ORIGINAL="${CLAUDE_DIR}/statusline-original.sh"
SETTINGS="${CLAUDE_DIR}/settings.json"
RUNNER="${CLAUDE_DIR}/plugins/marketplaces/agent-tracer/packages/runtime/bin/run-hook-claude.sh"
MARKER="# AGENT_TRACER_STATUSLINE_WRAPPER v1"
EXPECTED_CMD="bash ~/.claude/statusline-command.sh"

if [ ! -x "$RUNNER" ]; then
  echo "ERROR: agent-tracer plugin runner not found:" >&2
  echo "  $RUNNER" >&2
  echo "" >&2
  echo "Install the plugin first via Claude Code:" >&2
  echo "  /plugin marketplace add belljun3395/agent-tracer" >&2
  echo "  /plugin install agent-tracer-monitor@agent-tracer" >&2
  exit 1
fi

mkdir -p "$CLAUDE_DIR"

# ---------------------------------------------------------------------------
# 1. Install / refresh the wrapper script
# ---------------------------------------------------------------------------

if [ -f "$TARGET" ] && grep -Fq "$MARKER" "$TARGET"; then
  echo "Wrapper already installed (marker found):"
  echo "  $TARGET"
else
  if [ -f "$TARGET" ]; then
    TS=$(date +%s)
    BACKUP="${TARGET}.bak.${TS}"
    cp "$TARGET" "$BACKUP"
    cp "$TARGET" "$ORIGINAL"
    chmod +x "$ORIGINAL"
    echo "Existing status line backed up:"
    echo "  $BACKUP"
    echo "Existing logic preserved as:"
    echo "  $ORIGINAL  (sourced by the wrapper)"
  fi

  cat > "$TARGET" <<'WRAPPER'
#!/bin/sh
# AGENT_TRACER_STATUSLINE_WRAPPER v1
# Generated by scripts/install-statusline.sh — do not edit by hand.
# Combines the user's previous status line (if any) with the agent-tracer
# monitor segment. Re-run the installer to update.

input=$(cat)

base=""
if [ -x "${HOME}/.claude/statusline-original.sh" ]; then
  base=$(printf '%s' "$input" | sh "${HOME}/.claude/statusline-original.sh" 2>/dev/null || true)
fi

monitor=""
runner="${HOME}/.claude/plugins/marketplaces/agent-tracer/packages/runtime/bin/run-hook-claude.sh"
if [ -x "$runner" ]; then
  monitor=$(printf '%s' "$input" | "$runner" StatusLine 2>/dev/null || true)
fi

if [ -n "$base" ] && [ -n "$monitor" ]; then
  printf '%s \033[90m%s\033[0m' "$base" "$monitor"
elif [ -n "$monitor" ]; then
  printf '%s' "$monitor"
else
  printf '%s' "$base"
fi
WRAPPER

  chmod +x "$TARGET"
  echo ""
  echo "Installed wrapper:"
  echo "  $TARGET"
fi

# ---------------------------------------------------------------------------
# 2. Inspect ~/.claude/settings.json and report (or patch) statusLine state
# ---------------------------------------------------------------------------

if ! command -v python3 >/dev/null 2>&1; then
  echo ""
  echo "NOTE: python3 not found — cannot inspect or patch settings.json."
  echo "Add this block manually to ${SETTINGS}:"
  echo ""
  echo "  \"statusLine\": {"
  echo "    \"type\": \"command\","
  echo "    \"command\": \"${EXPECTED_CMD}\""
  echo "  }"
  echo ""
  echo "Then restart Claude Code."
  exit 0
fi

STATE="$(python3 - "$SETTINGS" "$EXPECTED_CMD" <<'PY'
import json, os, sys
path, expected = sys.argv[1], sys.argv[2]
if not os.path.exists(path):
    print("MISSING_FILE"); sys.exit(0)
try:
    with open(path) as f:
        data = json.load(f)
except Exception as e:
    print(f"INVALID_JSON:{e}"); sys.exit(0)
sl = data.get("statusLine")
if sl is None:
    print("NO_KEY"); sys.exit(0)
if not isinstance(sl, dict):
    print(f"WRONG_TYPE:{type(sl).__name__}"); sys.exit(0)
cmd = sl.get("command", "")
print("MATCH" if cmd == expected else f"MISMATCH:{cmd}")
PY
)"

echo ""
case "$STATE" in
  MATCH)
    echo "✓ settings.json already declares the statusLine wrapper."
    echo "  If the segment isn't visible yet, restart Claude Code."
    ;;
  NO_KEY)
    if [ "$APPLY" = "1" ]; then
      python3 - "$SETTINGS" "$EXPECTED_CMD" <<'PY'
import json, shutil, sys, time
path, expected = sys.argv[1], sys.argv[2]
shutil.copyfile(path, f"{path}.bak.{int(time.time())}")
with open(path) as f:
    data = json.load(f)
data["statusLine"] = {"type": "command", "command": expected}
with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PY
      echo "✓ Patched ${SETTINGS} — statusLine now points at the wrapper."
      echo "  A timestamped backup was created next to it (*.bak.*)."
      echo "  Restart Claude Code for the change to take effect."
    else
      cat <<EOF
=============================================================
  ACTION REQUIRED — wrapper installed but NOT yet active
=============================================================
${SETTINGS} has no "statusLine" key, so Claude Code will not
run the wrapper you just installed. Re-run with --apply to
patch settings.json automatically (with a backup), or add
this block manually as a top-level key:

  "statusLine": {
    "type": "command",
    "command": "${EXPECTED_CMD}"
  }

Then restart Claude Code.
EOF
    fi
    ;;
  MISMATCH:*)
    CURRENT="${STATE#MISMATCH:}"
    cat <<EOF
⚠ settings.json already has a "statusLine", pointing at:
    ${CURRENT}

The wrapper is designed to chain through an existing
statusline script (saved as ~/.claude/statusline-original.sh),
so you can safely repoint it. Update the command to:
    ${EXPECTED_CMD}

This script will NOT auto-patch when an existing statusLine is
present, even with --apply, to avoid clobbering custom setups.
EOF
    ;;
  MISSING_FILE)
    if [ "$APPLY" = "1" ]; then
      python3 - "$SETTINGS" "$EXPECTED_CMD" <<'PY'
import json, sys
path, expected = sys.argv[1], sys.argv[2]
with open(path, "w") as f:
    json.dump({"statusLine": {"type": "command", "command": expected}}, f, indent=2)
    f.write("\n")
PY
      echo "✓ Created ${SETTINGS} with a statusLine entry."
      echo "  Restart Claude Code for the change to take effect."
    else
      cat <<EOF
⚠ ${SETTINGS} does not exist.
Re-run with --apply to create it, or create it yourself with:

  {
    "statusLine": {
      "type": "command",
      "command": "${EXPECTED_CMD}"
    }
  }

Then restart Claude Code.
EOF
    fi
    ;;
  INVALID_JSON:*|WRONG_TYPE:*)
    echo "⚠ ${SETTINGS} could not be parsed safely (${STATE})."
    echo "  Fix the file by hand, then add this block:"
    echo ""
    echo "    \"statusLine\": {"
    echo "      \"type\": \"command\","
    echo "      \"command\": \"${EXPECTED_CMD}\""
    echo "    }"
    ;;
  *)
    echo "⚠ Unknown settings.json state: ${STATE}"
    ;;
esac
