/**
 * Claude Code Hook: PostCompact
 *
 * Fires after context compaction completes.
 * Supported matchers: "manual" | "auto" (compaction trigger).
 *
 * Stdin payload fields (ref: https://code.claude.com/docs/en/hooks#other-events):
 *   session_id       string  — unique session identifier
 *   hook_event_name  string  — "PostCompact"
 *   trigger          string  — "manual" or "auto"
 *   cwd              string  — current working directory
 *   transcript_path  string  — path to the session transcript JSONL
 *   permission_mode  string  — current permission mode
 *
 * NOTE: The following field is used below but is NOT in the official schema.
 * It appears to be an implementation extension available in practice:
 *   compact_summary  string? — summary generated by the compaction
 *
 * Blocking: PostCompact cannot block (exit 2 shows stderr but execution continues).
 *           Ref: https://code.claude.com/docs/en/hooks#exit-code-2-behavior-matrix
 *
 * This handler records the compaction summary in the Agent Tracer monitor
 * so the UI can display what was preserved after the context window was trimmed.
 */
import { getSessionId, hookLog, hookLogPayload, LANE, postJson, readStdinJson, resolveSessionIds, toTrimmedString } from "./common.js";

async function main(): Promise<void> {
    const payload = await readStdinJson();
    hookLogPayload("PostCompact", payload);
    const sessionId = getSessionId(payload);
    hookLog("PostCompact", "fired", { sessionId: sessionId || "(none)" });

    if (!sessionId) {
        hookLog("PostCompact", "skipped — no sessionId");
        return;
    }

    const ids = await resolveSessionIds(sessionId);
    const trigger = toTrimmedString(payload.trigger) || "auto";
    const summary = toTrimmedString(payload.compact_summary, 1000)
        || "Claude Code compacted the conversation history.";

    await postJson("/api/save-context", {
        taskId: ids.taskId,
        sessionId: ids.sessionId,
        title: "Context compacted",
        body: summary,
        lane: LANE.planning,
        metadata: { trigger, compactPhase: "after" }
    });
    hookLog("PostCompact", "save-context posted", { trigger });
}

void main().catch((err: unknown) => {
    hookLog("PostCompact", "ERROR", { error: String(err) });
});
