/**
 * DI tokens for the verification module's outbound dependencies.
 */
export const RULE_ACCESS_PORT = "VERIFICATION_RULE_ACCESS_PORT";
export const TIMELINE_EVENT_ACCESS_PORT = "VERIFICATION_TIMELINE_EVENT_ACCESS_PORT";
export const NOTIFICATION_PUBLISHER_PORT = "VERIFICATION_NOTIFICATION_PUBLISHER_PORT";
export const TURN_PERSISTENCE_PORT = "VERIFICATION_TURN_PERSISTENCE_PORT";
export const VERDICT_PERSISTENCE_PORT = "VERIFICATION_VERDICT_PERSISTENCE_PORT";
export const RULE_ENFORCEMENT_PERSISTENCE_PORT = "VERIFICATION_RULE_ENFORCEMENT_PERSISTENCE_PORT";
export const TURN_QUERY_PERSISTENCE_PORT = "VERIFICATION_TURN_QUERY_PERSISTENCE_PORT";
